layout_spectrum: 0.842950829770416
typography_spectrum: 0.8877022005617619
color:
  brandStrength: 0.18860779283568263
  lightness: 0.6775690051726997
  saturation: 0.5763894279953092
  rhythmicContrast: 0.41693988256156445
  brandColors:
    - '#2B3A42'
    - '#3F5765'
    - '#BDD4DE'
    - '#EFEFEF'
    - '#FF530D'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/addee515-f403-4e9a-9fd1-dd2f91a9f97f.png
name: Ingeniería de Hábitos
navigation:
  - name: Clientes
    id: 188ca4c6-4105-4201-a052-23221132eefc
    type: content
  - name: Casos de éxito
    id: cdc9996b-47ad-4ac5-8fa2-3b4a63d6617f
    type: content
title: Elimina los problemas en estrategias de cambio
description: Domina el poder de los hábitos
purpose:
  - type: contact
    url: 'mailto:info@undiaextra.com'
    label: Contáctanos para conocer más...
